### ISSUE TITLE
404 for New & Noteworthy pages

### ISSUE THREAD

**Issue by gireeshpunathil** [eclipse-platform/www.eclipse.org-eclipse-news#114]
source page: https://eclipseide.org/release/noteworthy/

inaccessible pages:
https://eclipse.dev/eclipse/news/4.28/platform.php
https://eclipse.dev/eclipse/news/4.28/jdt.php
https://eclipse.dev/eclipse/news/4.28/platform_isv.php
https://eclipse.dev/eclipse/news/4.28/pde.php

**Comment by jonahgraham** [comment]
Has the platform changed how they are publishing N&N entries? Or is this some other kind of error. The  https://eclipseide.org/release/noteworthy/ is generated from the URLs entered in the PMI, such as on https://projects.eclipse.org/projects/eclipse/releases/4.28.0:

![image](https://github.com/eclipse-platform/www.eclipse.org-eclipse-news/assets/679236/cae48330-d4f1-422b-bf0c-5b4cce695ec6)

The https://eclipseide.org/release/noteworthy/ page also has special logic for the Eclipse project to dig in an extra level deep. If the Eclipse project news has been restructured please advise and I will work with the Eclipse Webmaster to fix that logic.

**Comment by jonahgraham** [comment]
This looks like a problem related to the eclipse.org/eclipse -> eclipse.dev/eclipse migration.

I will start raising issue with Eclipse Webmaster on that.

**Comment by jonahgraham** [comment]
@Bananeweizen had already raised it in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3358. I am closing this issue as it is a webmaster fix.
