### ISSUE TITLE
Move N&N to wiki

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/www.eclipse.org-eclipse-news#18]
Do we need a repo for N&N? IMHO a wiki would be easier to use and update and also easier accessable for the end user.

My suggestion would be to stop using the HTML document and start using the wiki for N&N.

WDYT @laeubi and @mickaelistria

**Comment by laeubi** [comment]
Many projects (also Eclipse projects) use a RELEASE_NOTES.md file in their project root already. 

Also see

- https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
- https://github.com/release-drafter/release-drafter

**Comment by mickaelistria** [comment]
-1 for a wiki. It creates a separate silo that is harder to track and more easily out of sync than documentation directly inside repository. And with GitHub rendering .md directly, allowing links and so on, I don't see any added value for a wiki.

**Comment by vogella** [comment]
@mickaelistria what about using RELEASE_NOTES.md?

**Comment by mickaelistria** [comment]
I do like RELEASE_NOTES.md as well. However, it means we'd stop deploying them into the website or the help content, or that we'll need to translate .md to .html as part of the build. So it's not trivial to switch.

**Comment by laeubi** [comment]
@wimjongman has made some experiments with hugo (?) there is also https://github.com/Ashkanph/md-to-html

**Comment by vogella** [comment]
Just stop deploying them. We can place a link in the help to the wiki

**Comment by mickaelistria** [comment]
> Just stop deploying them. We can place a link in the help to the wiki

One benefit of the help is that it's working offline. Do we want to stop supporting offline help?

**Comment by vogella** [comment]
> > Just stop deploying them. We can place a link in the help to the wiki
> 
> One benefit of the help is that it's working offline. Do we want to stop supporting offline help?

I think N&N for a version you newly download (which you get online) does not add value if its available offline.

**Comment by mickaelistria** [comment]
>  you newly download (which you get online)

That's not true for everyone. In some companies or even projects, the tools are fetched by some people, placed into some space together with documentation, and people are supposed to just download and use them. Some of those companies/projects happens to have development environment that are offline for security reasons. So some users may like to get this info offline.
But that's also hypothetical, as the doc is not so easy to reach. We may configure the SDK so that N&N page from help is shown instead of the Welcome page, but that's another story.

**Comment by vogella** [comment]
Closing as we do not have consent.
