### ISSUE TITLE
Create N&N structure for 4.25

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/www.eclipse.org-eclipse-news#33]
@lak-proddev or @sravanlakkimsetti IIRC you have a script to create the content for the next N&N release? If that is true can you run it and publish the result?

**Comment by laeubi** [comment]
Please also consider:

- https://github.com/eclipse-platform/www.eclipse.org-eclipse-news/issues/12

**Comment by sravanlakkimsetti** [comment]
@lshanmug Do you have a script for this one?
