### ISSUE TITLE
Enable actions for this repository?

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/www.eclipse.org-eclipse-news#85]
I think one might want to automate the applyTemplate script on milestone creation, but I don'T see any actions enbaled, can someone enable these or who needs to give +1 for that ?

**Comment by mickaelistria** [comment]
I didn't see a way to enable it in settings; Please open an issue to Eclipse Foundation helpdesk about it.

**Comment by laeubi** [comment]
I have created: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2868

**Comment by mickaelistria** [comment]
Actions are there.
